name: test action
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zjutszl/my-cool-action@v1.0.0-rc.1
      - run: echo "That\'s the end of this action"
