name: test action
on:
  issue_comment:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: zjutszl/my-cool-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
